
web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/djangobackend
web_migrate:
  extends:
    service: web
  command: python manage.py migrate
  env_file: .env-local
web_run:
  extends:
    service: web
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"