# Generated by Django 3.1.7 on 2021-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.TextField(max_length=15)),
                ('password', models.TextField(max_length=15)),
                ('fullname', models.TextField(max_length=30)),
                ('ev_brand', models.TextField(max_length=20)),
                ('ev_registration_no', models.TextField(max_length=15)),
                ('ev_type', models.TextField(max_length=15)),
                ('ev_port_type', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_id', models.TextField(max_length=30)),
                ('user_id', models.TextField(max_length=15)),
                ('date', models.TextField(max_length=20)),
                ('time', models.TextField(max_length=10)),
                ('status', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.TextField(max_length=30)),
                ('contact', models.TextField(max_length=15)),
                ('supported_port_type', models.TextField(default='Type-A;Type-B;Type-C;Type-D;Type-E;Type-F', max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=20)),
                ('pincode', models.TextField(max_length=10)),
                ('latitude', models.TextField(max_length=50)),
                ('longitude', models.TextField(max_length=50)),
                ('slots_available', models.TextField(max_length=15, null=True)),
            ],
        ),
    ]
