# Generated by Django 3.1.7 on 2021-09-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataModel', '0002_remove_station_slots_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='station_id',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='DataModel.station'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='DataModel.appuser'),
        ),
    ]
