# Generated by Django 3.1.7 on 2021-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataModel', '0003_auto_20210926_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.TextField(default='Open', max_length=20),
        ),
    ]
