name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Google cloud -Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

        # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build & Publish
        run: |
         docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/chargepointapi:latest .
         docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/chargepointapi:latest

      - name: Deploy
        run: |
          gcloud run deploy chargepointapi \
          --region europe-west1 \
          --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/chargepointapi:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}